### PR TITLE
establish webhid transport only once, init first page wallet loading after App component mount

### PR DESCRIPTION
**Pull request by R0bi7**
This should fix the pagination issue (transport re-creation issue) as well as load the first page wallets.

### CODE REVIEW

**Comment by nymkappa** [comment]
I've tested it locally using `npm install ; npm start` with latest Chrome version (MacOS) and ledger Nano S. The address list is loading forever and stays empty. The ICX ledger app was open as well.

Is there anything I should do in particular in order to test this?

**Comment by R0bi7** [comment]
> I've tested it locally using `npm install ; npm start` with latest Chrome version (MacOS) and ledger Nano S. The address list is loading forever and stays empty. The ICX ledger app was open as well.
> 
> Is there anything I should do in particular in order to test this?

Executing `npm install` and `npm start` should do it. 
- Are you opening `http://localhost:3000/`?
- Is there any additional console log (error or anything similar)?
- Does clicking page 2 show the addresses?

**Comment by nymkappa** [comment]
> > I've tested it locally using `npm install ; npm start` with latest Chrome version (MacOS) and ledger Nano S. The address list is loading forever and stays empty. The ICX ledger app was open as well.
> > Is there anything I should do in particular in order to test this?
> 
> Executing `npm install` and `npm start` should do it.
> 
>     * Are you opening `http://localhost:3000/`?
> 
>     * Is there any additional console log (error or anything similar)?
> 
>     * Does clicking page 2 show the addresses?

* I'm opening http://localhost:3000/ (it opens automatically with `npm start` in Chrome)
* Console only shows warnings https://pastebin.com/kRJ75Gkb
* Clicking on page 2 button does not work (nothing happens)
* Additionally, I've made sure to remove iconex extension in Chrome to avoid conflict

**Comment by R0bi7** [comment]
I just pushed the commit which removed loading of first page addresses after Component is mounted as well as some improvements regarding transport creation. Now addresses should be showing when clicking around pages.

Library used for connecting with ledger (webhid) must be called in the context of an user interaction (like a "click" event). This is the reason first page is not showing initially, but is showing when clicking pagination buttons later on.

This is new addition that improves the security. See more on [@ledgerhq/hw-transport-webhid](https://www.npmjs.com/package/@ledgerhq/hw-transport-webhid).
I would advocate to move the code from this separate repository to the main Iconex repository so that Ledger connection modal is not embedded using iframe (which is btw security risk). This should be much more secure, scalable and would allow triggering Ledger connection through user interaction (click event, etc..)

**Comment by nymkappa** [comment]
I confirm addresses are properly loading now. I have to change page to load them. However it shows "NaN ICX" for all of them.

Iconex wallet will be deprecated in the coming weeks, but we want to provide a working version until then at least :)

**Comment by nymkappa** [comment]
We tried to deploy this branch but when trying to connect to ledger we got the following error in the console:
```{name: "TransportOpenUserCancelled", message: "Failed to execute 'getDevices' on 'HID': Access to…eature \"hid\" is disallowed by permissions policy.", stack: "Error\n    at new t (https://hardwallet.icon.founda….foundation/static/js/2.b271f48a.chunk.js:2:92974"}```

**Comment by R0bi7** [comment]
> I confirm addresses are properly loading now. I have to change page to load them. However it shows "NaN ICX" for all of them.
> 
> Iconex wallet will be deprecated in the coming weeks, but we want to provide a working version until then at least :)

The balances are Nan because this code tries to transmit event to get balances to parent (because in prod is embedded as iframe) which in this local environment does not exist.

**Comment by R0bi7** [comment]
> We tried to deploy this branch but when trying to connect to ledger we got the following error in the console:
> `{name: "TransportOpenUserCancelled", message: "Failed to execute 'getDevices' on 'HID': Access to…eature \"hid\" is disallowed by permissions policy.", stack: "Error\n at new t (https://hardwallet.icon.founda….foundation/static/js/2.b271f48a.chunk.js:2:92974"}`

I would assume this is the issue of iframe + webhid security restrictions.

**Comment by nymkappa** [comment]
Closing as the ledger integration has been fixed already. Thank you.

**Pull request closed without merging**
